/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary1;

import org.junit.Test;

import java.util.*;

import static org.junit.Assert.*;

public class Lab03Test {
   
}